# Generated by Django 2.1.5 on 2019-02-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20190227_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='openid',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
