# Generated by Django 2.1.5 on 2019-02-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20190227_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='renpin',
            field=models.BigIntegerField(blank=True, verbose_name='人品值'),
        ),
    ]
