# Generated by Django 2.1.5 on 2019-02-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20190227_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='is_delete',
            field=models.SmallIntegerField(default=0, verbose_name='1-删除，0-有效'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='is_deleted',
            field=models.SmallIntegerField(default=0, verbose_name='1-删除，0-有效'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='is_deleted',
            field=models.SmallIntegerField(default=0, verbose_name='1-删除，0-有效'),
        ),
    ]
