# Generated by Django 2.1.5 on 2019-02-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20190227_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='renpin',
            field=models.BigIntegerField(default=0, verbose_name='人品值'),
        ),
    ]
